output.elasticsearch:
  hosts: ["https://pmacho-elasticsearch:9200"]
  username: "elastic"
  password: "${ELASTIC_PASSWORD}"
  ssl:
    enabled: true
    certificate_authorities: ["/usr/share/filebeat/certs/ca/ca.crt"]

setup.kibana:
  host: "http://pmacho-kibana:5601"
  username: "elastic"
  password: "${ELASTIC_PASSWORD}"

filebeat.modules:
  - module: nginx
    access:
      enabled: true
      var.paths:
        - /logs/access.log
    error:
      enabled: true
      var.paths:
        - /logs/error.log
