services:
  pmacho-wiremock:
    image: wiremock/wiremock:latest
    ports:
      - 8080:8080
    volumes:
      - ./mappings:/home/wiremock/mappings
      - ./__files:/home/wiremock/__files
    restart: unless-stopped

